// Pasteboard: classify a change (what to record or why to skip), and the
// one-shot `paste` / `copy` commands.

import AppKit
import ApplicationServices
import Carbon.HIToolbox

let selfMarkerType = "dev.pcstyle.bettercast.self"
let maxClipBytes = 50 * 1024 * 1024

enum ClipDecision: Equatable {
    case skip(String)
    case text
    case image(String) // pasteboard type to read
}

let imageTypesInOrder = ["public.png", "public.tiff", "public.jpeg", "com.compuserve.gif", "public.heic", "org.webmproject.webp"]

/// Pure decision from the pasteboard's type list (first item's types plus
/// the pasteboard-level types). Order of checks is the contract's skip order.
func classifyPasteboard(types: [String], hasNonEmptyText: Bool, imagesEnabled: Bool) -> ClipDecision {
    let set = Set(types)
    if set.isEmpty { return .skip("empty") }
    if set.contains(selfMarkerType) { return .skip("self") }
    if set.contains("org.nspasteboard.ConcealedType") || set.contains("com.agilebits.onepassword") {
        return .skip("concealed")
    }
    if set.contains("org.nspasteboard.TransientType") || set.contains("de.petermaurer.TransientPasteboardType") {
        return .skip("transient")
    }
    if set.contains("org.nspasteboard.AutoGeneratedType") { return .skip("autogenerated") }
    // Copied files (Finder) come with an icon TIFF: record the name text, not the icon.
    let isFile = set.contains("public.file-url") || set.contains("NSFilenamesPboardType")
    if isFile { return hasNonEmptyText ? .text : .skip("unsupported") }
    // Text wins over a rendered picture of the same content (spreadsheets,
    // rich text); a browser image copy has no plain text and stays an image.
    let hasPlain = set.contains("public.utf8-plain-text") || set.contains("NSStringPboardType")
    if hasPlain && hasNonEmptyText { return .text }
    if let imageType = imageTypesInOrder.first(where: set.contains) {
        return imagesEnabled ? .image(imageType) : .skip("images-off")
    }
    if hasPlain { return .skip("empty") }
    return .skip("unsupported")
}

func isBlank(_ s: String) -> Bool {
    s.unicodeScalars.allSatisfy { CharacterSet.whitespacesAndNewlines.contains($0) }
}

// MARK: - Writing

/// Put a stored clip on the general pasteboard, tagged with the self marker
/// so our own watcher skips it. Images get PNG plus a TIFF fallback rep.
func writeClipToPasteboard(file: String, kind: String) throws {
    let url = URL(fileURLWithPath: file)
    let data = try Data(contentsOf: url)
    let pb = NSPasteboard.general
    switch kind {
    case "text":
        guard let text = String(data: data, encoding: .utf8) else { throw SpecError.bad("clip is not UTF-8 text") }
        pb.clearContents()
        pb.declareTypes([.string, NSPasteboard.PasteboardType(selfMarkerType)], owner: nil)
        pb.setString(text, forType: .string)
    case "image":
        guard let img = decodeImage(data) else { throw SpecError.bad("clip is not a readable image") }
        let png = data.starts(with: [0x89, 0x50, 0x4E, 0x47]) ? data : try encodePNG(img)
        let tiff = try encodeTIFF(img)
        pb.clearContents()
        pb.declareTypes([.png, .tiff, NSPasteboard.PasteboardType(selfMarkerType)], owner: nil)
        pb.setData(png, forType: .png)
        pb.setData(tiff, forType: .tiff)
    default:
        usage("--kind must be text or image")
    }
    pb.setData(Data(), forType: NSPasteboard.PasteboardType(selfMarkerType))
}

// MARK: - Commands

func runCopy(_ args: Args) -> Never {
    let file = args.required("file")
    let kind = args.required("kind")
    do {
        try writeClipToPasteboard(file: file, kind: kind)
    } catch {
        fail("copy-failed", "\(error)")
    }
    Out.line(["result", "copied"])
    exit(Exit.ok)
}

/// Key code that types "v" in the current keyboard layout (Dvorak, AZERTY,
/// ...); ANSI 9 when it cannot be determined.
func keyCodeForV() -> CGKeyCode {
    guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
          let raw = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else { return 9 }
    let layoutData = Unmanaged<CFData>.fromOpaque(raw).takeUnretainedValue() as Data
    return layoutData.withUnsafeBytes { buf -> CGKeyCode in
        guard let layout = buf.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return 9 }
        for code in 0..<128 {
            var dead: UInt32 = 0
            var chars = [UniChar](repeating: 0, count: 4)
            var len = 0
            let st = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDown), 0, UInt32(LMGetKbdType()),
                                    OptionBits(kUCKeyTranslateNoDeadKeysBit), &dead, chars.count, &len, &chars)
            if st == noErr && len == 1 && chars[0] == UniChar(("v" as Unicode.Scalar).value) {
                return CGKeyCode(code)
            }
        }
        return 9
    }
}

func frontmostPid() -> pid_t {
    NSWorkspace.shared.frontmostApplication?.processIdentifier ?? -1
}

func runPaste(_ args: Args) -> Never {
    let pidArg = args.required("pid")
    let file = args.required("file")
    let kind = args.required("kind")
    guard let pid = Int32(pidArg) else { usage("--pid must be a number") }
    do {
        try writeClipToPasteboard(file: file, kind: kind)
    } catch {
        fail("paste-failed", "\(error)")
    }
    guard AXIsProcessTrusted() else {
        Out.line(["result", "copied"])
        exit(Exit.needsAX)
    }
    if pid > 0 {
        guard let app = NSRunningApplication(processIdentifier: pid), !app.isTerminated else {
            Out.error("no-target", "target app \(pid) is not running; content left on the clipboard")
            Out.line(["result", "copied"])
            exit(Exit.failure)
        }
        app.activate(options: [])
        let deadline = Date().addingTimeInterval(0.5)
        while frontmostPid() != pid && Date() < deadline {
            RunLoop.current.run(until: Date().addingTimeInterval(0.02))
        }
        guard frontmostPid() == pid else {
            Out.error("not-front", "target app did not come to the front; content left on the clipboard")
            Out.line(["result", "copied"])
            exit(Exit.failure)
        }
    }
    // Let the target settle so the key event lands in its key window.
    RunLoop.current.run(until: Date().addingTimeInterval(0.05))
    let v = keyCodeForV()
    let src = CGEventSource(stateID: .combinedSessionState)
    guard let down = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: true),
          let up = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: false) else {
        fail("event-failed", "could not create the Cmd+V event")
    }
    down.flags = .maskCommand
    up.flags = .maskCommand
    down.post(tap: .cghidEventTap)
    up.post(tap: .cghidEventTap)
    Out.line(["result", "pasted"])
    exit(Exit.ok)
}

// MARK: - CI-only fixtures (BETTERCAST_CI=1; hosted runners only)

func requireCI() {
    guard ProcessInfo.processInfo.environment["BETTERCAST_CI"] == "1" else {
        fail("ci-only", "this command is for CI runners (set BETTERCAST_CI=1)", exit: Exit.usage)
    }
}

/// `debug-pasteboard --file <path> --kind text|image [--extra-type <uti>]`:
/// put synthetic content on the pasteboard like another app would (no self
/// marker). Images go on as uncompressed TIFF only, the worst case the
/// watcher must shrink. `--extra-type` adds e.g. org.nspasteboard.ConcealedType.
func runDebugPasteboard(_ args: Args) -> Never {
    requireCI()
    let file = args.required("file")
    let kind = args.required("kind")
    guard let data = FileManager.default.contents(atPath: file) else { fail("read", "cannot read \(file)") }
    let pb = NSPasteboard.general
    var types: [NSPasteboard.PasteboardType] = []
    let extra = args.optional("extra-type").map { NSPasteboard.PasteboardType($0) }
    pb.clearContents()
    switch kind {
    case "text":
        types = [.string] + (extra.map { [$0] } ?? [])
        pb.declareTypes(types, owner: nil)
        pb.setString(String(decoding: data, as: UTF8.self), forType: .string)
    case "image":
        guard let img = decodeImage(data), let tiff = try? encodeTIFF(img) else { fail("decode", "not an image: \(file)") }
        types = [.tiff] + (extra.map { [$0] } ?? [])
        pb.declareTypes(types, owner: nil)
        pb.setData(tiff, forType: .tiff)
        Out.line(["tiff-bytes", String(tiff.count)])
    default:
        usage("--kind must be text or image")
    }
    if let extra { pb.setData(Data(), forType: extra) }
    Out.line(["result", "set", String(pb.changeCount)])
    exit(Exit.ok)
}

/// `debug-key --code <carbonKeyCode> --mods <carbonMods>`: post one key
/// chord through the HID tap (fires our own global hotkeys on CI). Needs
/// Accessibility for the calling process; exit 3 without it.
func runDebugKey(_ args: Args) -> Never {
    requireCI()
    guard let code = UInt16(args.required("code")), let mods = UInt32(args.required("mods")) else { usage("bad --code/--mods") }
    guard AXIsProcessTrusted() else { Out.line(["ax", "0"]); exit(Exit.needsAX) }
    var flags: CGEventFlags = []
    if mods & 256 != 0 { flags.insert(.maskCommand) }
    if mods & 512 != 0 { flags.insert(.maskShift) }
    if mods & 2048 != 0 { flags.insert(.maskAlternate) }
    if mods & 4096 != 0 { flags.insert(.maskControl) }
    let src = CGEventSource(stateID: .hidSystemState)
    guard let down = CGEvent(keyboardEventSource: src, virtualKey: code, keyDown: true),
          let up = CGEvent(keyboardEventSource: src, virtualKey: code, keyDown: false) else { fail("event-failed", "CGEvent") }
    down.flags = flags
    up.flags = flags
    down.post(tap: .cghidEventTap)
    usleep(30_000)
    up.post(tap: .cghidEventTap)
    Out.line(["result", "posted"])
    exit(Exit.ok)
}
