// `selftest`: headless checks of the pure parts. Touches no OS state (no
// pasteboard, hotkeys, windows, Accessibility); writes only to a fresh
// temporary directory that it removes.

import Foundation

func runSelftest() -> Never {
    var failures: [String] = []
    var count = 0
    func check(_ ok: Bool, _ what: String) {
        count += 1
        if !ok { failures.append(what) }
    }

    // base64 (RFC 4648 vectors) and `-` for empty.
    let vectors: [(String, String)] = [("f", "Zg=="), ("fo", "Zm8="), ("foo", "Zm9v"), ("foobar", "Zm9vYmFy")]
    for (plain, enc) in vectors {
        check(b64(Data(plain.utf8)) == enc, "b64(\(plain))")
        check(unb64(enc) == Data(plain.utf8), "unb64(\(enc))")
    }
    check(b64(Data()) == "-" && unb64("-") == Data(), "empty base64 is -")
    check(unb64("not base64!") == nil, "bad base64 rejected")
    let unicode = "zażółć gęślą jaźń — ☃ 日本"
    check(unb64(b64(unicode, maxBytes: 4096)) == Data(unicode.utf8), "unicode base64 round trip")

    // sha256
    check(sha256Hex(Data("abc".utf8)) == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad", "sha256(abc)")
    check(sha256Hex(Data()) == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "sha256(empty)")

    // UTF-8 safe truncation (preview = first <= 240 bytes, never a cut scalar).
    let long = String(repeating: "ż", count: 200) // 400 bytes
    let pre = utf8Prefix(long, maxBytes: 240)
    check(pre.count == 240 && String(data: pre, encoding: .utf8) != nil, "utf8Prefix even cut")
    let odd = "a" + long
    let pre2 = utf8Prefix(odd, maxBytes: 240)
    check(pre2.count == 239 && String(data: pre2, encoding: .utf8) != nil, "utf8Prefix backs off a split scalar")

    // Line bounds: the largest chunk and preview lines stay under 4 KiB.
    let bigChunk = Data(repeating: 0xFF, count: maxChunkBytes)
    check(("chunk " + b64(bigChunk)).utf8.count + 1 < maxLineBytes, "chunk line bound")
    let previewLine = ["clip", "text", "1700000000000", String(repeating: "a", count: 64), "52428800",
                       b64(utf8Prefix(long, maxBytes: 240)), b64(String(repeating: "x", count: 5000), maxBytes: 600)].joined(separator: " ")
    check(previewLine.utf8.count + 1 < maxLineBytes, "clip text line bound")
    let chunks = utf8Chunks(Data(String(repeating: "日本語テキスト", count: 400).utf8), size: maxChunkBytes)
    check(chunks.allSatisfy { $0.count <= maxChunkBytes && String(data: $0, encoding: .utf8) != nil }, "utf8Chunks keep scalars whole")

    // Hotkey spec parsing.
    do {
        let specs = try parseHotkeySpec("launcher:49:2048,clipboard:9:2304,paste_next:9:4864,ask_ai:0:6400")
        check(specs == [
            HotkeySpec(token: "launcher", keyCode: 49, carbonMods: 2048),
            HotkeySpec(token: "clipboard", keyCode: 9, carbonMods: 2304),
            HotkeySpec(token: "paste_next", keyCode: 9, carbonMods: 4864),
            HotkeySpec(token: "ask_ai", keyCode: 0, carbonMods: 6400),
        ], "hotkey spec parse")
        check(try parseHotkeySpec("-").isEmpty, "hotkey spec -")
    } catch {
        check(false, "hotkey spec parse threw \(error)")
    }
    for bad in ["launcher:49", "nope:49:256", "launcher:200:256", "launcher:49:1", "launcher:49:256,launcher:1:256", "launcher:x:256"] {
        check((try? parseHotkeySpec(bad)) == nil, "hotkey spec rejects \(bad)")
    }

    // AI request parsing (asymmetric: two attachments, unicode path, multi-line prompt).
    let reqText = "provider codex\nbin \(b64("/opt/homebrew/bin/codex"))\nmodel -\nattach \(b64("/tmp/a b.png"))\nattach \(b64("/tmp/ż.txt"))\nprompt\nline one\nline two ☃\n"
    do {
        let r = try parseAIRequest(Data(reqText.utf8))
        check(r.provider == "codex" && r.bin == "/opt/homebrew/bin/codex" && r.model.isEmpty, "request header")
        check(r.attachments == ["/tmp/a b.png", "/tmp/ż.txt"], "request attachments")
        check(r.prompt == Data("line one\nline two ☃\n".utf8), "request prompt raw to EOF")
    } catch {
        check(false, "request parse threw \(error)")
    }
    check((try? parseAIRequest(Data("provider x\n".utf8))) == nil, "request without prompt rejected")
    check((try? parseAIRequest(Data("bogus 1\nprompt\nx".utf8))) == nil, "request with unknown key rejected")

    // Pasteboard classification (pure).
    check(classifyPasteboard(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"], hasNonEmptyText: true, imagesEnabled: true) == .skip("concealed"), "concealed skipped")
    check(classifyPasteboard(types: ["public.utf8-plain-text", "org.nspasteboard.TransientType"], hasNonEmptyText: true, imagesEnabled: true) == .skip("transient"), "transient skipped")
    check(classifyPasteboard(types: ["public.utf8-plain-text", "org.nspasteboard.AutoGeneratedType"], hasNonEmptyText: true, imagesEnabled: true) == .skip("autogenerated"), "autogenerated skipped")
    check(classifyPasteboard(types: ["public.utf8-plain-text", selfMarkerType], hasNonEmptyText: true, imagesEnabled: true) == .skip("self"), "self skipped")
    check(classifyPasteboard(types: ["public.utf8-plain-text"], hasNonEmptyText: false, imagesEnabled: true) == .skip("empty"), "blank text skipped")
    check(classifyPasteboard(types: [], hasNonEmptyText: false, imagesEnabled: true) == .skip("empty"), "no types skipped")
    check(classifyPasteboard(types: ["public.utf8-plain-text", "public.rtf"], hasNonEmptyText: true, imagesEnabled: true) == .text, "text recorded")
    check(classifyPasteboard(types: ["public.tiff", "public.png", "public.html"], hasNonEmptyText: false, imagesEnabled: true) == .image("public.png"), "image prefers png")
    check(classifyPasteboard(types: ["public.tiff"], hasNonEmptyText: false, imagesEnabled: false) == .skip("images-off"), "images off")
    check(classifyPasteboard(types: ["public.file-url", "public.tiff", "public.utf8-plain-text"], hasNonEmptyText: true, imagesEnabled: true) == .text, "copied file records name, not icon")
    check(classifyPasteboard(types: ["public.utf8-plain-text", "public.tiff"], hasNonEmptyText: true, imagesEnabled: true) == .text, "text wins over rendered image")
    check(classifyPasteboard(types: ["com.apple.something"], hasNonEmptyText: false, imagesEnabled: true) == .skip("unsupported"), "unknown unsupported")

    // Images: PNG round trip, TIFF -> PNG size, dedupe across source formats.
    let img = syntheticImage(width: 173, height: 61)
    do {
        let png = try encodePNG(img)
        guard let back = decodeImage(png) else { throw ImageError.decode }
        check(back.width == 173 && back.height == 61, "png round trip size")
        check(rgbaPixels(back) == rgbaPixels(img), "png round trip pixels")

        let tiff = try encodeTIFF(img)
        check(tiff.count >= 173 * 61 * 4, "tiff is uncompressed (>= 4 bytes/pixel), got \(tiff.count)")
        let fromTiff = try toPNG(tiff)
        let fromPng = try toPNG(png)
        check(fromTiff.width == 173 && fromTiff.height == 61, "tiff->png size")
        check(fromTiff.png.count * 4 < tiff.count, "tiff->png at least 4x smaller (\(tiff.count) -> \(fromTiff.png.count))")
        check(rgbaPixels(decodeImage(fromTiff.png)!) == rgbaPixels(img), "tiff->png pixels")
        check(sha256Hex(fromTiff.png) == sha256Hex(fromPng.png), "same pixels from tiff and png hash the same")

        let thumb = try thumbnailPNG(png, maxSide: 64)
        check(max(thumb.width, thumb.height) == 64, "thumbnail longest side 64 (got \(thumb.width)x\(thumb.height))")

        // Store once into a scratch dir: second store is a dedupe, not a rewrite.
        let tmpRoot = ProcessInfo.processInfo.environment["TMPDIR"] ?? NSTemporaryDirectory()
        let dir = URL(fileURLWithPath: tmpRoot).appendingPathComponent("bettercast-selftest-\(getpid())/clips")
        defer { try? FileManager.default.removeItem(at: dir.deletingLastPathComponent()) }
        let a = try storeImageClip(tiff, clipsDir: dir)
        let b = try storeImageClip(png, clipsDir: dir)
        check(a.created && !b.created && a.sha == b.sha, "image stored once, deduped")
        check(FileManager.default.fileExists(atPath: dir.appendingPathComponent("\(a.sha).thumb.png").path), "thumbnail stored")
        let t1 = try storeTextClip("Hello, 世界 ☃\n", clipsDir: dir)
        let t2 = try storeTextClip("Hello, 世界 ☃\n", clipsDir: dir)
        check(t1.created && !t2.created && t1.bytes == Data("Hello, 世界 ☃\n".utf8).count, "text stored once")
        let stored = try Data(contentsOf: dir.appendingPathComponent("\(t1.sha).txt"))
        check(sha256Hex(stored) == t1.sha, "text file name is its sha")
    } catch {
        check(false, "image checks threw \(error)")
    }

    if failures.isEmpty {
        Out.line(["selftest", "ok"])
        exit(Exit.ok)
    }
    for f in failures { Out.error("selftest", f) }
    Out.line(["selftest", "failed", String(failures.count) + "/" + String(count)])
    exit(Exit.failure)
}
