// Clipboard history index. The helper's watch process detects pasteboard
// changes, skips concealed / transient items (org.nspasteboard.ConcealedType,
// TransientType, AutoGeneratedType, our own `self` marker), writes the
// payload ONCE to <dataDir>/clips/<sha>.txt|.png (images re-encoded as PNG,
// deduplicated by sha) and emits one `clip` line. The core keeps only this
// index (preview, size, times) in the persisted Model, newest first.
//
// Removing a clip from the index queues its payload file for deletion
// (Model.deleteQueue, drained one Cmd.deleteFile at a time by update.ts);
// a file is only deleted when no remaining clip still points at it.

import { asciiBytes } from "@native-sdk/core";
import type { Settings } from "./shared.ts";
import type { Clip, ClipFile, ClipFileKind, QueueItem } from "./model.ts";
import { bump, bytesEqual, concat2, joinBytes } from "./bytes.ts";

export const DAY_MS = 86400000;
export const MAX_ITEMS_LIMIT = 5000;
export const MIN_ITEMS_LIMIT = 10;
export const MAX_RETENTION_DAYS = 3650;

/// Absolute payload path of a clip file.
export function filePath(dataDir: Uint8Array, kind: ClipFileKind, sha: Uint8Array): Uint8Array {
  const ext = kind === "image" ? asciiBytes(".png") : kind === "thumb" ? asciiBytes(".thumb.png") : asciiBytes(".txt");
  return joinBytes([dataDir, asciiBytes("clips"), concat2(sha, ext)], asciiBytes("/"));
}

export function clipPath(dataDir: Uint8Array, clip: Clip): Uint8Array {
  return filePath(dataDir, clip.kind, clip.sha);
}

/// The helper's 256 px thumbnail of an image clip (what the list shows).
export function thumbPath(dataDir: Uint8Array, clip: Clip): Uint8Array {
  return filePath(dataDir, clip.kind === "image" ? "thumb" : clip.kind, clip.sha);
}

export function kindWord(clip: Clip): Uint8Array {
  return clip.kind === "image" ? asciiBytes("image") : asciiBytes("text");
}

export function findClip(clips: readonly Clip[], id: number): Clip | null {
  return clips.find((c) => c.id === id) ?? null;
}

function sameFile(a: Clip, kind: ClipFileKind, sha: Uint8Array): boolean {
  const owner = kind === "thumb" ? "image" : kind;
  return a.kind === owner && bytesEqual(a.sha, sha);
}

export interface RecordResult {
  readonly clips: readonly Clip[];
  readonly nextId: number;
  /// false when the clip was ignored (images off, malformed).
  readonly recorded: boolean;
}

/// Add a new clip or bump an existing one with the same kind + sha
/// (dedupe: the existing record keeps its id, pin and firstMs, moves to
/// the front with lastMs = incoming.lastMs). Images are ignored while
/// settings.recordImages is off.
export function recordClip(clips: readonly Clip[], incoming: Clip, nextId: number, settings: Settings): RecordResult {
  if (incoming.kind === "image" && !settings.recordImages) return { clips: clips, nextId: nextId, recorded: false };
  if (incoming.sha.length !== 64) return { clips: clips, nextId: nextId, recorded: false };
  const existing = clips.find((c) => sameFile(c, incoming.kind, incoming.sha));
  if (existing !== undefined) {
    const bumped: Clip = {
      ...existing,
      lastMs: incoming.lastMs > existing.lastMs ? incoming.lastMs : existing.lastMs,
      preview: incoming.preview.length > 0 ? incoming.preview : existing.preview,
      sourceBundle: incoming.sourceBundle.length > 0 ? incoming.sourceBundle : existing.sourceBundle,
    };
    const rest = clips.filter((c) => c.id !== existing.id);
    return { clips: [bumped, ...rest], nextId: nextId, recorded: true };
  }
  const added: Clip = { ...incoming, id: nextId | 0 };
  return { clips: [added, ...clips], nextId: bump(nextId) | 0, recorded: true };
}

/// Move a clip to the front with lastMs = atMs (pasted/copied again).
export function touchClip(clips: readonly Clip[], id: number, atMs: number): readonly Clip[] {
  const c = clips.find((x) => x.id === id);
  if (c === undefined) return clips;
  const moved: Clip = { ...c, lastMs: atMs > c.lastMs && atMs <= 4102444800000 ? Math.trunc(atMs) : c.lastMs };
  return [moved, ...clips.filter((x) => x.id !== id)];
}

export function togglePin(clips: readonly Clip[], id: number): readonly Clip[] {
  return clips.map((c) => (c.id === id ? { ...c, pinned: !c.pinned } : c));
}

export interface PruneResult {
  readonly clips: readonly Clip[];
  readonly removed: readonly Clip[];
}

/// Drop unpinned clips older than retentionDays (0 = no age limit, and no
/// age pruning before the clock is known) and unpinned clips beyond
/// maxItems (newest kept). Pinned clips are never pruned.
export function pruneClips(clips: readonly Clip[], settings: Settings, nowMs: number): PruneResult {
  const cutoff = settings.retentionDays > 0 && nowMs > 0 ? nowMs - settings.retentionDays * DAY_MS : -1;
  const cap = settings.maxItems > 0 ? settings.maxItems : MAX_ITEMS_LIMIT;
  const kept: Clip[] = [];
  const removed: Clip[] = [];
  let unpinned = 0;
  for (const c of clips) {
    if (c.pinned) {
      kept.push(c);
      continue;
    }
    if ((cutoff >= 0 && c.lastMs < cutoff) || unpinned >= cap) {
      removed.push(c);
      continue;
    }
    unpinned += 1;
    kept.push(c);
  }
  if (removed.length === 0) return { clips: clips, removed: [] };
  return { clips: kept, removed: removed };
}

/// Remove one clip (by id) from the index.
export function removeClip(clips: readonly Clip[], id: number): PruneResult {
  const c = clips.find((x) => x.id === id);
  if (c === undefined) return { clips: clips, removed: [] };
  return { clips: clips.filter((x) => x.id !== id), removed: [c] };
}

/// Remove every unpinned clip.
export function clearUnpinned(clips: readonly Clip[]): PruneResult {
  return { clips: clips.filter((c) => c.pinned), removed: clips.filter((c) => !c.pinned) };
}

/// Append the payload files of `removed` to the delete queue (skipping
/// files a kept clip or the queue already references).
export function queueDeletes(queue: readonly ClipFile[], removed: readonly Clip[], kept: readonly Clip[]): readonly ClipFile[] {
  const out: ClipFile[] = queue.slice();
  for (const r of removed) {
    if (kept.some((k) => sameFile(k, r.kind, r.sha))) continue;
    if (out.some((f) => f.kind === r.kind && bytesEqual(f.sha, r.sha))) continue;
    out.push({ kind: r.kind, sha: r.sha });
    if (r.kind === "image") out.push({ kind: "thumb", sha: r.sha });
  }
  return out;
}

/// True when a live clip still points at this file (so it must stay).
export function fileInUse(clips: readonly Clip[], f: ClipFile): boolean {
  return clips.some((c) => sameFile(c, f.kind, f.sha));
}

/// Drop queue entries whose clip no longer exists.
export function pruneQueue(queue: readonly QueueItem[], clips: readonly Clip[]): readonly QueueItem[] {
  if (queue.every((q) => clips.some((c) => c.id === q.clipId))) return queue;
  return queue.filter((q) => clips.some((c) => c.id === q.clipId));
}
